[package]
name = "apex-sonata"
version = "0.1.0"
authors = ["AXAz0r <thealeksaradovic@gmail.com>"]

[dependencies]
rand = "0.4.2"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
serenity = "0.5"